[images]
  remote_images = [httpssource.unsplash.com., httpsimages.unsplash.com., httpsext.same-assets.com., httpsugc.same-assets.com.]

[build]
  command = bun run build
  publish = .next

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = true

[[plugins]]
  package = @netlifyplugin-nextjs